// generated by stet — source-hash: b0e4581d96fbcf567667feb7811ad6cc9903e5ddd7d4776790f1153bfc528296
// source: descriptor.json · do not hand-edit; regenerate instead.

import '@getstet/stet';

declare module '@getstet/stet' {
  interface StetRegistry {
    keys:
      | 'blog_intro'
      | 'brand__footer_address'
      | 'brand__logo'
      | 'brand__name'
      | 'brand__primary'
      | 'brand__radius'
      | 'contact_form_labels'
      | 'farewell_notice'
      | 'footer_links'
      | 'hero_body'
      | 'hero_headline'
      | 'newsletter__body'
      | 'newsletter__subject'
      | 'pricing_price'
      | 'pricing_tier_name'
      | 'receipt__body'
      | 'receipt__subject'
      | 'seo_home_desc'
      | 'seo_home_title'
      | 'seo_pricing_desc'
      | 'seo_pricing_title'
      | 'theme_mode'
      | 'welcome__body'
      | 'welcome__preheader'
      | 'welcome__subject';
  }
}
