import { describe, expect, it } from 'vitest';

import { miniDescriptor, miniSnapshot, mutable, readFixture } from '../conformance/fixture.js';
import {
  checkGeneratedCurrent,
  embeddedHash,
  generateDefaultsModule,
  generateRegistry,
  generatedBody,
} from '../src/codegen.js';
import { checkCurrency, loadSnapshot, snapshotSmells } from '../src/index.js';
import type { Descriptor, Snapshot } from '../src/index.js';

const descriptor = miniDescriptor();
const snapshot = miniSnapshot();

/** The emitted module is TypeScript wrapping a JSON object literal — read it back. */
function emittedDefaults(module: string): Snapshot {
  const body = generatedBody(module);
  return JSON.parse(body.slice(body.indexOf('{'), body.lastIndexOf('}') + 1)) as Snapshot;
}

describe('loadSnapshot', () => {
  it('accepts the committed fixture', () => {
    expect(Object.keys(snapshot)).toContain('default');
  });

  it('requires the default locale — it is what every other locale falls back to', () => {
    expect(() => loadSnapshot({ de: {} })).toThrowError(/default/);
  });

  it('does not reject on content shape: a bad committed value is quarantined at read time', () => {
    expect(() => loadSnapshot({ default: { brand__primary: 'rebeccapurple' } })).not.toThrow();
  });
});

describe('generateDefaultsModule', () => {
  it('names defaults.json as its source, not the descriptor', () => {
    const module = generateDefaultsModule(snapshot);
    expect(module.startsWith('// generated by stet — source-hash: ')).toBe(true);
    expect(module.split('\n')[1]).toContain('source: defaults.json');
    expect(embeddedHash(module)).not.toBe(embeddedHash(generateRegistry(descriptor).keysTs));
  });

  it('sorts locales and keys and ends with a newline', () => {
    const module = generateDefaultsModule(snapshot);
    const emitted = emittedDefaults(module);
    expect(Object.keys(emitted)).toEqual([...Object.keys(emitted)].sort());
    for (const values of Object.values(emitted)) {
      expect(Object.keys(values)).toEqual([...Object.keys(values)].sort());
    }
    expect(module.endsWith('as const;\n')).toBe(true);
  });

  it('regenerates byte-identically from the same JSON', () => {
    expect(generateDefaultsModule(mutable(snapshot))).toBe(generateDefaultsModule(snapshot));
  });

  it('turns one value change into one line of diff', () => {
    const edited = mutable(snapshot);
    edited['default']!['hero_headline'] = 'Never miss a post.';
    const before = generatedBody(generateDefaultsModule(snapshot)).split('\n');
    const after = generatedBody(generateDefaultsModule(edited)).split('\n');
    expect(after).toHaveLength(before.length);
    const changed = before.map((line, i) => (line === after[i] ? null : i)).filter((i) => i !== null);
    expect(changed).toHaveLength(1);
    expect(after[changed[0] as number]).toContain('Never miss a post.');
  });
});

describe('checkCurrency', () => {
  it('passes the fixture in both directions', () => {
    expect(checkCurrency(descriptor, snapshot)).toEqual({ missing: [], orphans: [], warnings: [] });
  });

  it('fails a descriptor key with no committed value', () => {
    const extended = mutable(descriptor);
    extended.keys['hero_kicker'] = { shape: 'text', target: 'web' };
    expect(checkCurrency(extended, snapshot).missing).toEqual(['hero_kicker']);
  });

  it('does not ask a derived key for a committed value', () => {
    expect(checkCurrency(descriptor, snapshot).missing).not.toContain('seo_home_title');
  });

  it('reports an orphan and modifies nothing', () => {
    const shrunk = mutable(descriptor);
    delete shrunk.keys['blog_intro'];
    const before = JSON.stringify(snapshot);
    const report = checkCurrency(shrunk, snapshot);
    expect(report.orphans).toEqual(['blog_intro']);
    expect(JSON.stringify(snapshot)).toBe(before);
  });

  it('reads both maps as OWN properties, so a prototype name is checked like any other', () => {
    // Assigned rather than written into the literal: `constructor` in an object
    // literal takes `Object.prototype`'s type, not the index signature's.
    const keys: Descriptor['keys'] = {};
    keys['constructor'] = { shape: 'text', target: 'web' };
    // Declared with no row: a bare `in` answers from the prototype and calls it
    // present, so the missing value never surfaces.
    expect(checkCurrency({ version: 1, keys }, { default: {} }).missing).toEqual(['constructor']);

    // And the orphan side is the same test in the other direction.
    const orphaned: Snapshot = { default: {} };
    orphaned['default']!['constructor'] = 'x';
    expect(checkCurrency({ version: 1, keys: {} }, orphaned).orphans).toEqual(['constructor']);
  });
});

describe('checkGeneratedCurrent', () => {
  const generate = (s: Snapshot) => generateDefaultsModule(s);

  it('reports current for a file generated from the source it names', () => {
    const file = generateDefaultsModule(snapshot);
    expect(checkGeneratedCurrent(file, snapshot, generate).status).toBe('current');
  });

  it('reports staleSource when the source moved and the file did not', () => {
    const file = generateDefaultsModule(snapshot);
    const edited = mutable(snapshot);
    edited['default']!['hero_headline'] = 'Something else entirely.';
    expect(checkGeneratedCurrent(file, edited, generate).status).toBe('staleSource');
  });

  it('reports handEdited when the hashes agree and the body does not', () => {
    const file = generateDefaultsModule(snapshot).replace(
      'Never miss a post again.',
      'Edited by hand.',
    );
    const check = checkGeneratedCurrent(file, snapshot, generate);
    expect(check.status).toBe('handEdited');
    expect(check.embedded).toBe(check.fresh);
  });

  it('applies to the registry and the ambient types the same way', () => {
    const keysTs = generateRegistry(descriptor).keysTs;
    const dts = generateRegistry(descriptor).dts;
    expect(checkGeneratedCurrent(keysTs, descriptor, (d) => generateRegistry(d).keysTs).status).toBe(
      'current',
    );
    expect(checkGeneratedCurrent(dts, descriptor, (d) => generateRegistry(d).dts).status).toBe(
      'current',
    );
    expect(
      checkGeneratedCurrent(`${dts}\nexport {};\n`, descriptor, (d) => generateRegistry(d).dts)
        .status,
    ).toBe('handEdited');
  });

  it('reports staleSource for a file with no stet header at all', () => {
    expect(checkGeneratedCurrent('export const DEFAULTS = {};\n', snapshot, generate)).toMatchObject(
      { status: 'staleSource', embedded: null },
    );
  });
});

describe('people never enter the snapshot', () => {
  it('emits only what the snapshot holds, and the snapshot only what the descriptor declares', () => {
    const emitted = emittedDefaults(generateDefaultsModule(snapshot));
    expect(Object.keys(emitted)).toEqual(Object.keys(snapshot).sort());
    for (const [locale, values] of Object.entries(emitted)) {
      expect(Object.keys(values)).toEqual(Object.keys(snapshot[locale] ?? {}).sort());
    }
    expect(checkCurrency(descriptor, snapshot).orphans).toEqual([]);
  });

  it('has no path for a contact record to arrive without the descriptor declaring it', () => {
    const contaminated = mutable(snapshot);
    contaminated['default']!['newsletter_signups'] = {
      email: 'someone@example.com',
      consent: 'granted',
    };
    expect(checkCurrency(descriptor, contaminated).orphans).toEqual(['newsletter_signups']);
    const warnings = snapshotSmells(contaminated);
    expect(warnings).toHaveLength(1);
    expect(warnings[0]?.code).toBe('contact_record_smell');
    expect(warnings[0]?.key).toBe('newsletter_signups');
  });

  it('leaves a clean snapshot unflagged', () => {
    expect(snapshotSmells(snapshot)).toEqual([]);
  });

  it('does not flag a labels record — one marker is site copy, not a person', () => {
    const labels = mutable(snapshot);
    labels['default']!['contact_form_labels'] = { email: 'Your email address', name: 'Your name' };
    expect(snapshotSmells(labels)).toEqual([]);
  });
});

describe('the fixture on disk', () => {
  it('is what the tests read — no in-memory substitute', () => {
    expect((readFixture('defaults.json') as Snapshot)['default']?.['hero_headline']).toBe(
      'Never miss a post again.',
    );
  });
});
