import { createHash } from 'node:crypto';

import type { Descriptor, Shape } from './types.js';

/**
 * The generated-file header. Every artifact states its own source, because the
 * registry is generated from the descriptor and the defaults module from the
 * snapshot — a reader who cannot tell which file to regenerate from is stuck.
 */
export function generatedHeader(source: string, hash: string): string {
  return (
    `// generated by stet — source-hash: ${hash}\n` +
    `// source: ${source} · do not hand-edit; regenerate instead.\n`
  );
}

const HEADER_LINES = 2;
const HASH_PATTERN = /^\/\/ generated by stet — source-hash: ([0-9a-f]{64})$/;

/** The embedded hash, or null when the text carries no stet header. */
export function embeddedHash(fileText: string): string | null {
  const first = fileText.split('\n')[0] ?? '';
  return HASH_PATTERN.exec(first)?.[1] ?? null;
}

/** Everything below the header — what a hand edit changes and a hash cannot see. */
export function generatedBody(fileText: string): string {
  return fileText.split('\n').slice(HEADER_LINES).join('\n');
}

/**
 * sha256 over the source's canonical JSON — object keys sorted at every depth,
 * so a reformatted or reordered source hashes identically and only a real
 * content change reports stale.
 */
export function sourceHash(obj: unknown): string {
  return createHash('sha256').update(JSON.stringify(canonicalize(obj))).digest('hex');
}

/**
 * Object keys sorted at every depth. `sourceHash` hashes over it, and the CLI's
 * deterministic JSON writer serializes through it — one sorter, so a hash and
 * an emitted artifact can never disagree about what canonical means.
 */
export function canonicalize(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(canonicalize);
  if (value !== null && typeof value === 'object') {
    const source = value as Record<string, unknown>;
    const out: Record<string, unknown> = {};
    for (const key of Object.keys(source).sort()) out[key] = canonicalize(source[key]);
    return out;
  }
  return value;
}

/**
 * The shapes whose resolved value IS a string — the five arms of the validator's
 * own shape table that return a string schema. `number` resolves to a number and
 * `list` and `record` to structured values, so a map typed over string values
 * has to refuse those three.
 *
 * Membership is by SHAPE rather than a hand-kept list of keys, so a ninth shape
 * places itself by what its value is and cannot drift from `shapeSchema`.
 *
 * Typed over `Shape`, like `TEXT_SHAPES`: a misspelled member is a compile
 * error rather than a union that is silently one key short.
 */
const STRING_SHAPES: ReadonlySet<Shape> = new Set<Shape>(['text', 'richtext', 'media', 'enum', 'color']);

/**
 * The typed registry: `keys.ts` for runtime and type use, and the ambient
 * `.d.ts` that makes an unregistered key a compile error. Both are always
 * emitted — a plain-JS host typechecks against the ambient types in its editor,
 * while the offline checks stay the guarantee.
 */
export function generateRegistry(d: Descriptor): { keysTs: string; dts: string } {
  const keys = Object.keys(d.keys).sort();
  for (const key of keys) {
    // The schema constrains key names; a hand-built descriptor does not meet it,
    // and emitting a key that needs escaping would emit broken TypeScript.
    if (!/^[A-Za-z0-9_]+$/.test(key)) {
      throw new Error(`cannot generate a registry for key "${key}": key names are [A-Za-z0-9_] only`);
    }
  }
  const header = generatedHeader('descriptor.json', sourceHash(d));

  // Read through `Object.entries`: a bare index or `in` on a descriptor parsed
  // from JSON answers `constructor` and `__proto__` from the prototype chain.
  const stringKeys = Object.entries(d.keys)
    .filter(([, def]) => STRING_SHAPES.has(def.shape))
    .map(([key]) => key)
    .sort();

  const keysTs =
    header +
    '\n' +
    'export const KEYS = [\n' +
    keys.map((k) => `  '${k}',\n`).join('') +
    '] as const;\n' +
    '\n' +
    'export type ContentKey = (typeof KEYS)[number];\n' +
    '\n' +
    'export const STRING_KEYS = [\n' +
    stringKeys.map((k) => `  '${k}',\n`).join('') +
    '] as const;\n' +
    '\n' +
    'export type StringKey = (typeof STRING_KEYS)[number];\n';

  const union =
    keys.length === 0 ? '    keys: never;\n' : `    keys:\n${keys.map((k) => `      | '${k}'`).join('\n')};\n`;

  const dts =
    header +
    '\n' +
    "import '@getstet/stet';\n" +
    '\n' +
    "declare module '@getstet/stet' {\n" +
    '  interface StetRegistry {\n' +
    union +
    '  }\n' +
    '}\n';

  return { keysTs, dts };
}
