// generated by stet — source: descriptor.schema.json (the canonical contract).
// Do not hand-edit; run `npm run codegen:schema` instead.
export const DESCRIPTOR_SCHEMA = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://stet.dev/descriptor.schema.json",
  "title": "stet descriptor",
  "description": "The portable contract naming every piece of content a product says. Language-neutral JSON: any consumer can read it without a JavaScript runtime. The project id is not here — it lives in stet.config.json and reaches the core as a call argument.",
  "type": "object",
  "required": [
    "version",
    "keys"
  ],
  "additionalProperties": false,
  "properties": {
    "version": {
      "description": "Descriptor schema version, parsed by stet_meta.schema_version.",
      "type": "integer",
      "minimum": 1
    },
    "keys": {
      "type": "object",
      "propertyNames": {
        "$ref": "#/$defs/keyName"
      },
      "additionalProperties": {
        "$ref": "#/$defs/keyDef"
      }
    },
    "pages": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#/$defs/pageDef"
      }
    },
    "templates": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#/$defs/templateDef"
      }
    }
  },
  "$defs": {
    "keyName": {
      "description": "Keys name content, never position. Slot keys flatten as <template>__<slot>.",
      "type": "string",
      "pattern": "^[a-z0-9]+(?:_{1,2}[a-z0-9]+)*$"
    },
    "keyDef": {
      "type": "object",
      "required": [
        "shape",
        "target"
      ],
      "additionalProperties": false,
      "dependentRequired": {
        "derivesFrom": [
          "tmpl"
        ],
        "tmpl": [
          "derivesFrom"
        ]
      },
      "allOf": [
        {
          "if": {
            "properties": {
              "shape": {
                "const": "enum"
              }
            },
            "required": [
              "shape"
            ]
          },
          "then": {
            "required": [
              "values"
            ]
          },
          "else": {
            "not": {
              "required": [
                "values"
              ]
            }
          }
        }
      ],
      "properties": {
        "shape": {
          "description": "richtext and media are reserved in phase 1 — declared here, consumed by no phase-1 surface.",
          "enum": [
            "text",
            "list",
            "record",
            "enum",
            "color",
            "number",
            "richtext",
            "media"
          ]
        },
        "target": {
          "enum": [
            "web",
            "html-email",
            "telegram-md2"
          ]
        },
        "limits": {
          "description": "A per-key setting, not a universal obligation.",
          "type": "object",
          "required": [
            "max",
            "severity"
          ],
          "additionalProperties": false,
          "properties": {
            "max": {
              "type": "integer",
              "minimum": 1
            },
            "severity": {
              "enum": [
                "advisory",
                "hard"
              ]
            }
          }
        },
        "budget": {
          "description": "Max rendered lines per device. Advisory in phase 1; measured verdicts are phase 2. Publish is never silently blocked by a budget.",
          "type": "object",
          "additionalProperties": false,
          "minProperties": 1,
          "properties": {
            "desktop": {
              "type": "integer",
              "minimum": 1
            },
            "mobile": {
              "type": "integer",
              "minimum": 1
            }
          }
        },
        "values": {
          "description": "Required if and only if shape is enum.",
          "type": "array",
          "minItems": 1,
          "uniqueItems": true,
          "items": {
            "type": "string"
          }
        },
        "vars": {
          "description": "The whitelist of {{variables}} this key may interpolate.",
          "type": "array",
          "uniqueItems": true,
          "items": {
            "type": "string"
          }
        },
        "tags": {
          "description": "The number of numbered placeholder tags (<1>…</1>) a value of this key carries, one per descendant element of the marked element, numbered depth-first; the save gate keeps them whole.",
          "type": "integer",
          "minimum": 1
        },
        "derivesFrom": {
          "type": "string"
        },
        "tmpl": {
          "description": "The derivation template. Must contain {v}, the source key's resolved value.",
          "type": "string"
        },
        "pages": {
          "description": "The pages this key renders on. Plural: a shared key appears on several.",
          "type": "array",
          "uniqueItems": true,
          "items": {
            "type": "string"
          }
        },
        "label": {
          "type": "string"
        },
        "help": {
          "type": "string"
        },
        "previewUrl": {
          "type": "string"
        },
        "section": {
          "type": "string"
        },
        "agentPublish": {
          "description": "The key-level pin to draft-only, regardless of the project-level mode. Only false is expressible: a key that omits it follows the project.",
          "const": false
        },
        "pack": {
          "description": "Provenance. It never namespaces the key or alters its identity; removing a pack untags, never deletes.",
          "type": "string"
        }
      }
    },
    "pageDef": {
      "description": "Structure only. The editable SEO fields are ordinary content keys the page record references.",
      "type": "object",
      "required": [
        "route"
      ],
      "additionalProperties": false,
      "properties": {
        "route": {
          "type": "string"
        },
        "parent": {
          "type": "string"
        },
        "locales": {
          "type": "array",
          "uniqueItems": true,
          "items": {
            "type": "string"
          }
        },
        "seo": {
          "description": "The editable SEO fields, as references. Each names an ordinary content key — declared, never inferred from a naming convention.",
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "title": {
              "description": "the content key carrying this field",
              "type": "string"
            },
            "description": {
              "description": "the content key carrying this field",
              "type": "string"
            },
            "robots": {
              "description": "the content key carrying this field",
              "type": "string"
            },
            "canonical": {
              "description": "the content key carrying this field",
              "type": "string"
            },
            "ogImage": {
              "description": "the content key carrying this field",
              "type": "string"
            },
            "ogImageAlt": {
              "description": "the content key carrying this field",
              "type": "string"
            }
          },
          "examples": [
            {
              "title": "seo_home_title",
              "description": "seo_home_desc"
            }
          ]
        },
        "jsonLd": {
          "description": "Simultaneously the emission spec and the visible-content check's input.",
          "type": "object",
          "required": [
            "type",
            "bindings"
          ],
          "additionalProperties": false,
          "properties": {
            "type": {
              "type": "string"
            },
            "bindings": {
              "type": "object",
              "additionalProperties": {
                "type": "string"
              }
            }
          },
          "examples": [
            {
              "type": "Offer",
              "bindings": {
                "name": "pricing_tier_name",
                "price": "pricing_price"
              }
            }
          ]
        }
      }
    },
    "templateDef": {
      "description": "Template-level facts. No descriptor construct holds email markup — the host owns that.",
      "type": "object",
      "required": [
        "class",
        "trigger",
        "slots"
      ],
      "additionalProperties": false,
      "properties": {
        "class": {
          "description": "A descriptor property, not editable content. Marketing requires {{unsubscribe_url}} in scope.",
          "enum": [
            "transactional",
            "marketing"
          ]
        },
        "trigger": {
          "enum": [
            "form",
            "app-event",
            "schedule",
            "ci",
            "manual"
          ]
        },
        "clock": {
          "description": "The Level-1 timing metadata, e.g. \"T-3d before trial end\". The host runs the clock.",
          "type": "string"
        },
        "sender": {
          "description": "A sender-profile name declared in stet.config.json.",
          "type": "string"
        },
        "slots": {
          "description": "Each slot resolves to a key named <template>__<slot>.",
          "type": "array",
          "minItems": 1,
          "uniqueItems": true,
          "items": {
            "type": "string"
          }
        },
        "wrapperProvides": {
          "description": "The tokens the host's render path already carries, e.g. unsubscribe_url. stet doctor verifies the claim against the real render path.",
          "type": "array",
          "uniqueItems": true,
          "items": {
            "type": "string"
          }
        },
        "render": {
          "description": "The host module and export that consume these slots, with sample props sufficient to invoke it. stet email verify renders through this pointer and stet doctor walks its import closure; an entry without one is declared but not centrally verifiable.",
          "type": "object",
          "required": [
            "file",
            "export",
            "sampleProps"
          ],
          "additionalProperties": false,
          "properties": {
            "file": {
              "description": "The module holding the slot-consuming shell, relative to the app package root.",
              "type": "string",
              "minLength": 1
            },
            "export": {
              "description": "The exported function the slots are passed to.",
              "type": "string",
              "minLength": 1
            },
            "sampleProps": {
              "description": "One props object sufficient to invoke the export. Descriptor data like every other proposal — reviewable and hand-editable.",
              "type": "object"
            }
          }
        }
      }
    }
  }
};
