// Regenerates src/descriptor-schema.generated.ts from descriptor.schema.json
// (the canonical file — operator ruling 2026-08-18). Run: npm run codegen:schema
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const schema = JSON.parse(readFileSync(join(root, 'descriptor.schema.json'), 'utf8'));
const body = JSON.stringify(schema, null, 2);
writeFileSync(
  join(root, 'src', 'descriptor-schema.generated.ts'),
  `// generated by stet — source: descriptor.schema.json (the canonical contract).\n` +
  `// Do not hand-edit; run \`npm run codegen:schema\` instead.\n` +
  `export const DESCRIPTOR_SCHEMA = ${body};\n`,
);
console.log('descriptor-schema.generated.ts written from descriptor.schema.json');
